# Generated by Django 5.2.17 on 2026-09-10 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('budget', models.PositiveIntegerField(verbose_name='مبلغ قرارداد')),
                ('cost', models.PositiveIntegerField(verbose_name='هزینه اجرا')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('done', 'تمام شده'), ('cancel', 'لغو شده')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.customer', verbose_name='مشتری')),
            ],
        ),
    ]
