# Generated by Django 5.2.17 on 2026-09-17 08:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_followup_alter_customer_options_customer_address_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='مهلت تحویل'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='شرح پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ قرارداد (تومان)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه اجرا (تومان)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('hold', 'متوقف'), ('done', 'تمام\u200cشده'), ('cancel', 'لغوشده')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'deadline'], name='project_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['customer', '-created_at'], name='project_customer_date_idx'),
        ),
    ]
