# Generated by Django 5.2.17 on 2026-09-17 08:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان پیگیری')),
                ('kind', models.CharField(choices=[('call', 'تماس تلفنی'), ('meeting', 'جلسه'), ('email', 'ایمیل'), ('visit', 'بازدید محل'), ('other', 'سایر')], default='call', max_length=20, verbose_name='نوع پیگیری')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'مهم'), ('urgent', 'فوری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('due_at', models.DateTimeField(verbose_name='زمان سررسید')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('completed', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'پیگیری',
                'verbose_name_plural': 'پیگیری\u200cها',
                'ordering': ['completed', 'due_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created'], 'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ارتباط'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('referral', 'معرفی'), ('instagram', 'اینستاگرام'), ('website', 'وب\u200cسایت'), ('phone', 'تماس ورودی'), ('exhibition', 'نمایشگاه'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نحوه آشنایی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='شرکت / سازمان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید بین ۷ تا ۱۵ رقم باشد و می\u200cتواند با + شروع شود.', regex='^\\+?[0-9]{7,15}$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('contact', 'تماس گرفته شده'), ('deal', 'در حال مذاکره'), ('done', 'تبدیل شده'), ('lost', 'از دست رفته')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='مالک پرونده'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'status'], name='customer_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', '-created'], name='customer_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('user', 'phone'), name='uniq_customer_phone_per_user'),
        ),
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='followup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['created_by', 'completed', 'due_at'], name='followup_owner_due_idx'),
        ),
    ]
